require_relative '../setup'
require_relative './exercise_1'
require_relative './exercise_2'
require_relative './exercise_3'
require_relative './exercise_4'

puts "\n----------------- Exercise 5 -----------------------\n\n"

# Exercise 5: Calculations

#   Output the total revenue for the entire company (all stores), using Active Record's .sum calculation method.
#   On the next line, also output the average annual revenue for all stores.
#   Output the number of stores that are generating $1M or more in annual sales. 
#   Chain together where and size (or count) Active Record methods.


puts "\nTotal revenue generated by all stores is: #{Store.sum(:annual_revenue)}"

puts "\nAverage amount generated by each location: #{Store.average(:annual_revenue)}"

puts "\nTotal # of stores generating over 1M in annual revenue: #{Store.where("annual_revenue >= ?", 1000000).count}"